version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    restart: always
    ports:
        - "5432:5432"
    env_file:
      - database.env # configure postgres
    volumes:
      - /home/cloud_user/Desktop/data-temp:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
volumes:
  database-data: # named volumes can be managed easier using docker-compose